INSERT INTO USERS (ID, LOGIN, ROLE, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (1, 'admin2', 1, 'admin', 'ivan', 'ivanov');
INSERT INTO USERS (ID, LOGIN, ROLE, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (2, 'nagibator98', 1, 'admin98', 'dmitry', 'sidorov');
INSERT INTO USERS (ID, LOGIN, ROLE, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (3, 'dd04072001', 1, 'alex0407', 'alex', 'wolf');
INSERT INTO USERS (ID, LOGIN, ROLE, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (4, 'fedor_traktorist', 1, 'fedor78', 'fedor', 'ignatev');
INSERT INTO USERS (ID, LOGIN, ROLE, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (5, 'selo78', 1, 'chichik78', 'anton', 'chichikov');

INSERT INTO CONTACTS(ID, FRIEND_FROM_ID, FRIEND_TO_ID, IS_ACCEPTED, REQUEST_MESSAGE) VALUES (1, 1, 2, false, 'приффки');
INSERT INTO CONTACTS(ID, FRIEND_FROM_ID, FRIEND_TO_ID, IS_ACCEPTED, REQUEST_MESSAGE) VALUES (2, 2, 3, false, 'хей чувак');
INSERT INTO CONTACTS(ID, FRIEND_FROM_ID, FRIEND_TO_ID, IS_ACCEPTED, REQUEST_MESSAGE) VALUES (3, 3, 1, false, 'напиши строчна');
INSERT INTO CONTACTS(ID, FRIEND_FROM_ID, FRIEND_TO_ID, IS_ACCEPTED, REQUEST_MESSAGE) VALUES (4, 2, 4, false, 'займи косарь плиз');
INSERT INTO CONTACTS(ID, FRIEND_FROM_ID, FRIEND_TO_ID, IS_ACCEPTED, REQUEST_MESSAGE) VALUES (5, 5, 1, false, 'встреча завтра');

INSERT INTO MESSAGES(ID, SENDER_ID,RECIPIENT_ID, BODY, CREATED_AT) VALUES (1, 2, 1, 'досвидос', '2019-02-13 17:03:07');
INSERT INTO MESSAGES(ID, SENDER_ID,RECIPIENT_ID, BODY, CREATED_AT) VALUES (2, 3, 2, 'дарова', '2019-02-13 17:08:15');
INSERT INTO MESSAGES(ID, SENDER_ID,RECIPIENT_ID, BODY, CREATED_AT) VALUES (3, 3, 2, 'что хотел?', '2019-02-13 17:59:13');
INSERT INTO MESSAGES(ID, SENDER_ID,RECIPIENT_ID, BODY, CREATED_AT) VALUES (4, 4, 2, 'ты мне прошлый займ не вернул', '2019-02-13 18:57:11');
INSERT INTO MESSAGES(ID, SENDER_ID,RECIPIENT_ID, BODY, CREATED_AT) VALUES (5, 1, 5, 'на память не жалуюсь', '2019-02-13 18:59:45');